name: Daily login

on:
  schedule:
  - cron: "0 17 * * *"
  workflow_dispatch:
  
env:
  MIHOYO_COOKIE: ${{ secrets.MIHOYO_COOKIE }}

jobs:
  report:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]
        
    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - run: npm ci
    - run: npm i puppeteer
    - run: node daily-login/genshin.js
    - run: node daily-login/honkai.js
