# This workflow will do a screen shot from the url provided
# For more information see: https://github.com/marketplace/actions/screenshots-ci-action
name: screenshots ci actions
on:
  push:
    branches:
    - main

jobs:
  screenshots:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install puppeteer-headful
      uses: mujo-code/puppeteer-headful@master
      env:
        CI: 'true'
    - name: screenshots-desktop-facebook
      uses: flameddd/screenshots-ci-action@v1.1.1
      with:
        url: https://logo.honcho.com.au/a/w/honcho/logos?t=company+ABCD&tags=cat,dog,sun,cloud,mountain&types=icon,initial&colors=green,dark-blue&email=test@test.com
        fullPage: true
    - uses: actions/upload-artifact@v2
      with:
        name: Download-desktop-screenshots
        path: screenshots
    - run: rm ./screenshots/*

    - name: screenshots-mobile-facebook
      uses: flameddd/screenshots-ci-action@v1.1.1
      with:
        url: https://logo.honcho.com.au/a/w/honcho/logos?t=company+ABCD&tags=cat,dog,sun,cloud,mountain&types=icon,initial&colors=green,dark-blue&email=test@test.com
        devices: iPhone 6,iPhone 6 landscape,Nexus 7,Pad Pro,Galaxy S III landscape,iPad Pro landscape
        noDesktop: true
        fullPage: true
    - uses: actions/upload-artifact@v2
      with:
        path: screenshots
        name: Download-mobile-screenshots
    - run: rm ./screenshots/*
